import type { CatalogItem } from "../types/catalog.types";

export const CATALOG_ITEMS: CatalogItem[] = [
  {
    id: "array",
    name: "Array",
    type: "data-structure",
    categoryId: "linear-memory",
    description: "Memoria contigua representada como bloques secuenciales.",
    tags: ["lineal", "memoria", "base"],
  },
  {
    id: "stack",
    name: "Stack",
    type: "data-structure",
    categoryId: "linear-memory",
    description: "Estructura LIFO: último en entrar, primero en salir.",
    tags: ["lineal", "lifo"],
  },
  {
    id: "queue",
    name: "Queue",
    type: "data-structure",
    categoryId: "linear-memory",
    description: "Estructura FIFO: primero en entrar, primero en salir.",
    tags: ["lineal", "fifo"],
  },
  {
    id: "linked-list",
    name: "Linked List",
    type: "data-structure",
    categoryId: "linear-memory",
    description: "Nodos conectados mediante referencias espaciales.",
    tags: ["nodos", "punteros"],
  },
  {
    id: "binary-search-tree",
    name: "Binary Search Tree",
    type: "data-structure",
    categoryId: "tree-systems",
    description: "Árbol binario organizado por comparación de valores.",
    tags: ["árbol", "búsqueda"],
  },
  {
    id: "heap",
    name: "Heap",
    type: "data-structure",
    categoryId: "tree-systems",
    description: "Estructura jerárquica para obtener mínimos o máximos eficientemente.",
    tags: ["árbol", "prioridad"],
  },
  {
    id: "graph-basic",
    name: "Graph básico",
    type: "data-structure",
    categoryId: "graph-systems",
    description: "Red de nodos conectados mediante aristas.",
    tags: ["grafos", "redes"],
  },

  {
    id: "bubble-sort",
    name: "Bubble Sort",
    type: "algorithm",
    categoryId: "sorting-basics",
    description: "Ordenamiento por comparación adyacente.",
    complexity: "O(n²)",
    tags: ["ordenamiento", "comparación"],
  },
  {
    id: "insertion-sort",
    name: "Insertion Sort",
    type: "algorithm",
    categoryId: "sorting-basics",
    description: "Ordenamiento mediante inserción progresiva.",
    complexity: "O(n²)",
    tags: ["ordenamiento", "comparación"],
  },
  {
    id: "quick-sort",
    name: "Quick Sort",
    type: "algorithm",
    categoryId: "efficient-sorting",
    description: "Ordenamiento basado en pivote y partición.",
    complexity: "O(n log n)",
    tags: ["ordenamiento", "divide-y-vencerás"],
  },
  {
    id: "merge-sort",
    name: "Merge Sort",
    type: "algorithm",
    categoryId: "efficient-sorting",
    description: "Ordenamiento por división y mezcla de subconjuntos.",
    complexity: "O(n log n)",
    tags: ["ordenamiento", "divide-y-vencerás"],
  },
  {
    id: "heap-sort",
    name: "Heap Sort",
    type: "algorithm",
    categoryId: "efficient-sorting",
    description: "Ordenamiento basado en la estructura Heap.",
    complexity: "O(n log n)",
    tags: ["ordenamiento", "heap"],
  },
  {
    id: "counting-sort",
    name: "Counting Sort",
    type: "algorithm",
    categoryId: "distribution-sorting",
    description: "Ordenamiento no comparativo basado en frecuencias.",
    complexity: "O(n + k)",
    tags: ["ordenamiento", "distribución"],
  },
];