import type { CatalogCategory } from "../types/catalog.types";

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  {
    id: "linear-memory",
    domainId: "data-structures",
    title: "Memoria lineal",
    description: "Estructuras secuenciales organizadas por posición o flujo.",
    order: 1,
  },
  {
    id: "tree-systems",
    domainId: "data-structures",
    title: "Árboles y jerarquías",
    description: "Estructuras ramificadas con relaciones padre-hijo.",
    order: 2,
  },
  {
    id: "graph-systems",
    domainId: "data-structures",
    title: "Grafos y redes",
    description: "Sistemas de nodos conectados mediante aristas.",
    order: 3,
  },
  {
    id: "associative-memory",
    domainId: "data-structures",
    title: "Memoria asociativa",
    description: "Estructuras basadas en llaves, búsqueda rápida y mapeo.",
    order: 4,
  },
  {
    id: "probabilistic-structures",
    domainId: "data-structures",
    title: "Estructuras probabilísticas",
    description: "Estructuras compactas para pertenencia aproximada.",
    order: 5,
  },
  {
    id: "advanced-structures",
    domainId: "data-structures",
    title: "Estructuras avanzadas",
    description: "Estructuras especializadas para casos complejos.",
    order: 6,
  },

  {
    id: "sorting-basics",
    domainId: "algorithms",
    title: "Ordenamiento básico",
    description: "Algoritmos introductorios de comparación visual.",
    order: 10,
  },
  {
    id: "efficient-sorting",
    domainId: "algorithms",
    title: "Ordenamiento eficiente",
    description: "Algoritmos con mejor rendimiento y estrategias avanzadas.",
    order: 11,
  },
  {
    id: "distribution-sorting",
    domainId: "algorithms",
    title: "Ordenamiento por distribución",
    description: "Algoritmos no comparativos basados en conteo o agrupación.",
    order: 12,
  },
  {
    id: "hybrid-sorting",
    domainId: "algorithms",
    title: "Ordenamiento híbrido",
    description: "Algoritmos que combinan varias estrategias.",
    order: 13,
  },
  {
    id: "parallel-sorting",
    domainId: "algorithms",
    title: "Ordenamiento paralelo",
    description: "Algoritmos pensados para concurrencia o GPU.",
    order: 14,
  },
  {
    id: "graph-traversal",
    domainId: "algorithms",
    title: "Recorridos en grafos",
    description: "Algoritmos para explorar redes de nodos.",
    order: 15,
  },
  {
    id: "pathfinding",
    domainId: "algorithms",
    title: "Búsqueda de caminos",
    description: "Algoritmos para encontrar rutas posibles u óptimas.",
    order: 16,
  },
  {
    id: "tree-operations",
    domainId: "algorithms",
    title: "Operaciones sobre árboles",
    description: "Procesos de inserción, búsqueda, balanceo y recorrido.",
    order: 17,
  },
];